include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
  
  language:
    strict-casts: true
    strict-raw-types: false
    strict-inference: false

linter:
  rules:
    # Flutter/Dart best practices
    prefer_const_literals_to_create_immutables: true
    sort_unnamed_constructors_first: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_constructors_first: false
    sort_pub_dependencies: false
    prefer_single_quotes: false
    flutter_style_todos: false
    discarded_futures: false
    avoid_print: true

    # Code organization
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_spread_collections: true

    # Security and reliability
    avoid_catches_without_on_clauses: false
    use_key_in_widget_constructors: true

    # Readability
    avoid_unnecessary_containers: true
    sort_child_properties_last: true
    prefer_relative_imports: false
    sized_box_for_whitespace: true

    # Performance
    avoid_redundant_argument_values: true
    prefer_null_aware_operators: true
    prefer_if_null_operators: true
    unnecessary_null_checks: true

    # Maintainability
    public_member_api_docs: false # Set to true for library packages
    lines_longer_than_80_chars: false

    # Documentation

    # Flutter specific
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_void_to_null: true

    # Disabled rule (your requested)
    avoid_multiple_declarations_per_line: false
    eol_at_end_of_file: false
