// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChpV2NzZO2Q6VR0kVWm6YE85s3e1J5eEg',
    appId: '1:675136919387:android:3cfa2778c6eb494bd36c7e',
    messagingSenderId: '675136919387',
    projectId: 'exam-pyq-5e9c1',
    storageBucket: 'exam-pyq-5e9c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjdMb-iGnjWfPHP-zcoxRHiaxwAjJ_6wg',
    appId: '1:675136919387:ios:65fc63fd2afd9c57d36c7e',
    messagingSenderId: '675136919387',
    projectId: 'exam-pyq-5e9c1',
    storageBucket: 'exam-pyq-5e9c1.firebasestorage.app',
    iosClientId: '675136919387-vth4te023irjhdclq968lidgj7g2mhfe.apps.googleusercontent.com',
    iosBundleId: 'com.harud.exampyq.examPyq',
  );
}
